name: docker-build-control

# Build control when "base" changes, or when any files in the control folder are
# modified
on:
  workflow_run:
    workflows: ["docker-build-base"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:
  push:
    paths:
      - 'autonomy_core/control/**'
    branches: [master]
  # DO NOT add a schedule. This build will be triggered by base schedule.

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: github.repository == 'kumarrobotics/kr_autonomous_flight'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.repository == 'kumarrobotics/kr_autonomous_flight'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./autonomy_core/control/Dockerfile
          platforms: ${{ github.repository == 'kumarrobotics/kr_autonomous_flight' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: ${{ github.repository == 'kumarrobotics/kr_autonomous_flight' }}
          tags: kumarrobotics/autonomy:control

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
